networks:
  balionis-network:
    name: balionis-network

services:
  local-prometheus:
    image: prom/prometheus
    container_name: local-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./docker/config/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - balionis-network
  local-grafana:
    image: grafana/grafana
    container_name: local-grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker/config/grafana:/etc/grafana/provisioning/datasources
    networks:
      - balionis-network
volumes:
  prom_data: