app:
  service:
    name: ${spring.application.name}
    kafka:
      topic-name: my-messages
      timeout-seconds: 10

server:
  port: 9090
  max-http-request-header-size: 16KB
  shutdown: graceful

spring:
  application:
    name: arvydas-lesson11-producer
  kafka:
    bootstrap-servers: "localhost:3333"
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      "schema.registry.url": ${KAFKA_SCHEMA_REGISTRY_URL:mock://}

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "actuator/prometheus"
        health: "actuator/health"
        info: "actuator/info"
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
            - diskSpace
            # - kafkaState (TODO: build a custom state)
        readiness:
          include:
            - readinessState
            # - db (TODO: add after db is added)
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m
  server:
    port: 9001

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "${JAEGER_TRACING_URL:mock://}"
