---
openapi: 3.0.0
info:
  title: Swagger Dainius lesson9 Producer
  description: |
    This is a sample Dainius Lesson 8 Producer.
  termsOfService: http://dainius.balionis.com/terms/
  version: 1.0.0
servers:
  - url: https://dainius.balionis.com/api/1.0.0
tags:
  - name: producer
    description: Access to Dainius message producer
paths:
  /api/v1/producer/message:
    post:
      operationId: sendMessage
      description: send message
      tags:
        - producer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SendMessageRequest:
      type: object
      properties:
        messageId:
          type: string
          format: uuid
        message:
          type: string
          maxLength: 1000
      required:
        - messageId
        - message
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
