app:
  service:
    name: ${spring.application.name}
    kafka:
      topic-name: my-messages
      timeout-seconds: 10

server:
  port: 9090
  max-http-request-header-size: 16KB
  shutdown: graceful

spring:
  application:
    name: dainius-lession8-producer
  kafka:
    bootstrap-servers: "localhost:3333"
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "spring.json.type.mapping": "message:com.balionis.dainius.lesson10.producer.stream.model.KafkaMessage"
