app:
  service:
    name: myProducerService
    kafka:
      topic-name: my-messages
      timeout-seconds: 10

server:
  port: 9090
  max-http-request-header-size: 16KB
  shutdown: graceful

kafka:
  bootstrap-servers: "localhost:3333"