app:
  service:
    name: myService

server:
  port: 9090
  max-http-request-header-size: 16KB
  shutdown: graceful

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://local-mysql:3306/arvydas_db
    username: mysql_adm
    password: mysql_pwd
