version: '3.5'

networks:
  balionis-network:
    name: balionis-network

services:
  local-postgres:
    container_name: local-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pwd
      POSTGRES_DB: arvydas_db
    volumes:
      - ./postgres-setup:/docker-entrypoint-initdb.d
    networks:
      - balionis-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
  local-liquibase:
    image: liquibase/liquibase:4.29.2
    container_name: local-liquibase
    command: update --url=jdbc:postgresql://local-postgres:5432/arvydas_db?user=postgres'&'password=postgres_pwd --changelog-file=changelog/db.changelog-master.yaml
    volumes:
      - ../src/main/resources/db/changelog:/liquibase/changelog
      - ../src/main/resources/db/changeset:/liquibase/db/changeset
    networks:
      - balionis-network
    depends_on:
      local-postgres:
        condition: service_healthy
  local-service:
    container_name: local-service
    image: arvydas-lesson06:latest
    ports:
      - "9091:9090"
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker -Dlogback.configurationFile=/app/config/logback-docker.xml"
    volumes:
      - ./docker/config:/app/config
    networks:
      - balionis-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://local-service:9090/api/v1/heartbeat" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    depends_on:
      local-postgres:
        condition: service_healthy
