---
openapi: 3.0.0
info:
  title: Swagger Dainius lesson12 producer
  description: |
    This is a sample Dainius Lesson 12 producer
  termsOfService: http://dainius.balionis.com/terms/
  version: 1.0.0
servers:
  - url: https://dainius.balionis.com/api/1.0.0
tags:
  - name: producer
    description: Access to Dainius producer
paths:
  /api/v1/heartbeat:
    get:
      operationId: getHeartbeat
      description: get heartbeat
      tags:
        - producer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHeartbeatResponse'
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetHeartbeatResponse:
      type: object
      properties:
        checkTs:
          type: integer
      required:
        - checkTs
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
