---
openapi: 3.0.0
info:
  title: Swagger Dainius lesson9 Consumer
  description: |
    This is a sample Dainius Lesson 8 Consumer.
  termsOfService: http://dainius.balionis.com/terms/
  version: 1.0.0
servers:
  - url: https://dainius.balionis.com/api/1.0.0
tags:
  - name: consumer
    description: Access to Dainius message consumer
paths:
  /api/v1/consumer/message:
    get:
      operationId: listMessages
      description: list messages
      tags:
        - consumer
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: false
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessageResponse'
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Message:
      type: object
      properties:
        messageId:
          type: string
          format: uuid
        message:
          type: string
          maxLength: 1000
      required:
        - messageId
        - message
    MessageArray:
      type: array
      items:
        $ref: '#/components/schemas/Message'
    GetMessageResponse:
      type: object
      properties:
        messages:
          $ref: '#/components/schemas/MessageArray'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
