networks:
  balionis-network:
    name: balionis-network

services:
  local-producer:
    container_name: local-producer
    hostname: local-producer
    image: dainius-lesson12-producer:latest
    ports:
      - "9091:9090"
      - "9001:9000"
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker -Dlogback.configurationFile=/app/config/logback-docker.xml"
      JAEGER_TRACING_URL: "http://local-jaeger:9411/api/v2/spans"
    volumes:
      - ./docker/config/producer:/app/config
    networks:
      - balionis-network
    profiles:
      - service
  local-consumer:
    container_name: local-consumer
    hostname: local-consumer
    image: dainius-lesson12-consumer:latest
    ports:
      - "9092:9090"
      - "9002:9000"
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker -Dlogback.configurationFile=/app/config/logback-docker.xml"
      JAEGER_TRACING_URL: "http://local-jaeger:9411/api/v2/spans"
    volumes:
      - ./docker/config/consumer:/app/config
    networks:
      - balionis-network
    profiles:
      - service
  local-prometheus:
    image: prom/prometheus:latest
    container_name: local-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./docker/config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - balionis-network
    profiles:
      - monitoring
  local-grafana:
    image: grafana/grafana:latest
    container_name: local-grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker/config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    networks:
      - balionis-network
    depends_on:
      - local-prometheus
    profiles:
      - monitoring
  local-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: local-jaeger
    ports:
      - "16686:16686" # the Jaeger UI
      - "9411:9411"   # the Zipkin collector http
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - balionis-network
    profiles:
      - monitoring
volumes:
  prometheus_data: