app:
  service:
    name: ${spring.application.name}
    kafka:
      topic-name: my-messages
      timeout-seconds: 10

server:
  port: 9090
  max-http-request-header-size: 16KB
  shutdown: graceful

spring:
  application:
    name: dainius-lession8-producer
  kafka:
    bootstrap-servers: "localhost:3333"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
