version: '3.5'

networks:
  balionis-network:
    name: balionis-network

volumes:
  balionis-data:
    name: balionis-data

services:
  local-mysql:
    container_name: local-mysql
    image: mysql:8.4.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_USER: mysql_adm
      MYSQL_PASSWORD: mysql_pwd
      MYSQL_DATABASE: arvydas_db
    networks:
      - balionis-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - balionis-data:/var/lib/mysql
  local-liquibase:
    image: liquibase/liquibase:4.29.2
    container_name: local-liquibase
    command: update --url=jdbc:mysql://local-mysql:3306/arvydas_db?user=root'&'password=root_pwd --changelog-file=changelog/db.changelog-master.yaml
    environment:
      INSTALL_MYSQL: true
    volumes:
      - ../src/main/resources/db/changelog:/liquibase/changelog
      - ../src/main/resources/db/changeset:/liquibase/db/changeset
    networks:
      - balionis-network
    depends_on:
      local-mysql:
        condition: service_healthy
  local-service:
    container_name: local-service
    image: arvydas-lesson07:latest
    ports:
      - "9091:9090"
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker -Dlogback.configurationFile=/app/config/logback-docker.xml"
    volumes:
      - ./docker/config:/app/config
    networks:
      - balionis-network
    depends_on:
      local-mysql:
        condition: service_healthy