app:
  service:
    name: myConsumerService
    pageSize: 100
    kafka:
      topic-name: my-messages

server:
  port: 9090
  max-http-request-header-size: 16KB
  shutdown: graceful

kafka:
  bootstrap-servers: "localhost:3333"
  polling-timeout: 3000
  concurrency: 3
