---
openapi: 3.0.0
info:
  title: Swagger arvydas Lesson4
  description: |
    This is a sample arvydas Lesson 4 server.
  termsOfService: http://arvydas.balionis.com/terms/
  version: 1.0.0
servers:
  - url: https://arvydas.balionis.com/api/1.0.0
tags:
  - name: moving
    description: Access to arvydas moving calculator
paths:
  /api/v1/moving:
    get:
      operationId: getMoving
      description: return moving formula (sum|avg) on cached numbers
      tags:
        - moving
      responses:
        "200":
          description: return moving formula result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMovingResponse'
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: addNumber
      description: add a number to moving cache
      tags:
        - moving
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddNumberRequest'
      responses:
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetMovingResponse:
      type: object
      properties:
        number:
          type: number
          format: double
    AddNumberRequest:
      type: object
      properties:
        number:
          type: number
          format: double
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
