---
openapi: 3.0.0
info:
  title: Swagger arvydas lesson12 consumer
  description: |
    This is a sample arvydas Lesson 12 consumer
  termsOfService: http://arvydas.balionis.com/terms/
  version: 1.0.0
servers:
  - url: https://arvydas.balionis.com/api/1.0.0
tags:
  - name: heartbeat
    description: Access to arvydas consumer heartbeat
paths:
  /api/v1/heartbeat:
    get:
      operationId: getHeartbeat
      description: get heartbeat
      tags:
        - heartbeat
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHeartbeatResponse'
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetHeartbeatResponse:
      type: object
      properties:
        checkTs:
          type: string
          format: date-time
      required:
        - checkTs
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
