app:
  service:
    name: ${spring.application.name}
    pageSize: 100
    kafka:
      topic-name: my-messages
      concurrency: 3

server:
  port: 9090
  max-http-request-header-size: 16KB
  shutdown: graceful

spring:
  application:
    name: dainius-lession8-consumer
  kafka:
    bootstrap-servers: "localhost:3333"
    consumer:
      isolation-level: read_committed
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: ${spring.application.name}
      client-id: ${spring.application.name}
      fetch-max-wait: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.type.mapping": "message:com.balionis.dainius.lesson10.consumer.stream.model.KafkaMessage"
