version: '3.5'

networks:
  balionis:
    name: balionis

services:
  service1:
    image: arvydas-lesson05:latest
    ports:
      - "9090:8080"
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker -Dlogback.configurationFile=/app/config/logback-docker.xml"
    volumes:
      - ./docker/config:/app/config